In [1]:
import numpy as np
import os
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree

In [2]:
corpus_train_pos = []
f = open("cornellmoviedataset/train_pos.txt", "r")
data = f.read()
corpus_train_pos = data.strip(" ").split("\n")
f.close()
print(len(corpus_train_pos))

12500


In [3]:
corpus_train_neg = []
f = open("cornellmoviedataset/train_neg.txt", "r")
data = f.read()
corpus_train_neg = data.strip(" ").split("\n")
f.close()
print(len(corpus_train_neg))

12500


In [4]:
corpus_train = []
for i in range(len(corpus_train_pos)):
    corpus_train.append(corpus_train_pos[i])

In [5]:
print(len(corpus_train))

12500


In [6]:
for i in range(len(corpus_train_neg)):
    corpus_train.append(corpus_train_neg[i])

In [7]:
print(len(corpus_train))

25000


In [8]:
y_train=np.zeros(25000)
y_train[0:12500]=1

In [9]:
corpus_test_pos = []
f = open("cornellmoviedataset/test_pos.txt", "r")
data = f.read()
corpus_test_pos = data.strip(" ").split("\n")
f.close()
print(len(corpus_test_pos))

12500


In [10]:
corpus_test_neg = []
f = open("cornellmoviedataset/test_neg.txt", "r")
data = f.read()
corpus_test_neg = data.strip(" ").split("\n")
f.close()
print(len(corpus_test_neg))

12500


In [11]:
y_test=np.zeros(25000)
y_test[0:12500]=1

In [12]:
corpus_test = []
for i in range(len(corpus_test_pos)):
    corpus_test.append(corpus_test_pos[i])

In [13]:
for i in range(len(corpus_test_neg)):
    corpus_test.append(corpus_test_neg[i])

In [14]:
print(len(corpus_test))

25000


In [15]:
accu_svm=0
accu_nb=0
accu_knn=0

In [ ]:
vectorizer = TfidfVectorizer(min_df=5,encoding='utf-8', max_df = 0.8, sublinear_tf=True, use_idf=True,stop_words='english')
train_corpus_tf_idf = vectorizer.fit_transform(corpus_train) 
test_corpus_tf_idf = vectorizer.transform(corpus_test)

In [20]:
import sklearn
model1 = sklearn.svm.SVC()
model1.fit(train_corpus_tf_idf,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
model2 = KNeighborsClassifier(n_neighbors=5)
model2.fit(train_corpus_tf_idf,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [18]:
model3 = LogisticRegression()
model3.fit(train_corpus_tf_idf,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
model1.score(test_corpus_tf_idf,y_test)

0.67108000000000001

In [17]:
 model2.score(test_corpus_tf_idf,y_test)

0.68888000000000005

In [19]:
model3.score(test_corpus_tf_idf,y_test)

0.88460000000000005

In [84]:
print("The SVC result is:")
print(confusion_matrix(y_test,result1))

The SVC result is:
[[10960  1540]
 [ 1755 10745]]


In [85]:
print("The KNN result is:")
print(confusion_matrix(y_test,result2))

The KNN result is:
[[8591 3909]
 [4367 8133]]


In [86]:
print("The Logistic Regression result is:")
print(confusion_matrix(y_test,result3))

The Logistic Regression result is:
[[11000  1500]
 [ 1385 11115]]


In [87]:
print(float(sum(result1==y_test)/25000))

0.8682


In [19]:
print(float(sum(result2==y_test)/25000))

0.66896


In [89]:
print(float(sum(result3==y_test)/25000))

0.8846


In [ ]:
import sklearn
model4 = sklearn.svm.SVC(kernel='linear')
model4.fit(train_corpus_tf_idf,y_train)

In [ ]:
model4.score(test_corpus_tf_idf,y_test)

In [ ]:
import sklearn
from sklearn import tree
model5 = tree.DecisionTreeClassifier()
model5.fit(train_corpus_tf_idf,y_train)
model5.score(test_corpus_tf_idf,y_test)